[package]
name = "synthy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# add some dependencies here
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug" }
rand = "0.8"