backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "toml-frontmatter"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page.html"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Description", name: "description", widget: "text"}
      - {body: "Body", name: "body", widget: "markdown"}
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        fields:
          - label: "Authors"
            name: "authors"
            widget: "list"
            field:
              - {label: "Author", name: "author", widget: "string"}
          - label: "Tags"
            name: "tags"
            widget: "list"
            field:
              - {label: "Tag", name: "tag", widget: "string"}
          - label: "Categories"
            name: "categories"
            widget: "list"
            field:
              - {label: "Category", name: "category", widget: "string"}